name: Build & Deploy to Kubernetes

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_TARGET_PLATFORM: linux/arm/v8

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure Docker Buildx
        run: |
          docker buildx create --name mybuilder
          docker buildx use mybuilder
          docker buildx inspect --bootstrap

      - uses: feavy/deploy@main
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          GITHUB_USERNAME: feavy
          GITHUB_TOKEN: ${{ secrets.PAT }}
          DOCKERFILE_PATH: .
          DOCKER_IMAGE: discord-plays-pokemon:latest
          DEPLOYMENT: deployment.yml
          PLATFORM: arm64
          TLS_CRT: ${{ secrets.TLS_CRT }}
          TLS_KEY: ${{ secrets.TLS_KEY }}

      - name: Restart deployment
        run: kubectl rollout restart deployment discord-plays-pokemon --namespace feavy
